prometheus:
  prometheusSpec:
    resources:
      requests:
        cpu: "100m"
        memory: "256Mi"
      limits:
        cpu: "200m"
        memory: "512Mi"

grafana:
  resources:
    requests:
      cpu: "50m"
      memory: "100Mi"
    limits:
      cpu: "100m"
      memory: "200Mi"

alertmanager:
  enabled: false
